version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${APP_DEBUG_PORT}:${APP_DEBUG_PORT}'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mariadb
      - mongodb
    restart: always
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_USER: ${MARIADB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    ports:
      - '${MARIADB_HOST_PORT}:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - '${MONGODB_HOST_PORT}:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  # mongo-express:
  #   image: mongo-express
  #   container_name: hazitrip_mongo_express
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_BASICAUTH_USERNAME: admin
  #     ME_CONFIG_BASICAUTH_PASSWORD: secret
  #   ports:
  #     - '8081:8081'
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '${RABBITMQ_HOST_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT}:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  mariadb-data:
  mongodb-data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
